obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.405, -0.255], [0.405, -0.255], [0.405, 0.255], [-0.405, 0.255]]
inflation_radius: 0.75
transform_tolerance: 0.5
use_dijkstra: True
use_quadratic: True 

observation_sources: scan
scan:
  sensor_frame: base_link
  data_type: LaserScan
  topic: /scan
  marking: true
  clearing: true
map_type: costmap
