TrajectoryPlannerROS:
  max_vel_x: 0.8
  min_vel_x: -0.2
  max_vel_theta: 1.8
  min_vel_theta: -1.8
  min_in_place_vel_theta: 0.6
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  holonomic_robot: false
  meter_scoring: true
  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.35
  